# Generated by Django 3.2.2 on 2022-08-30 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wish_list',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('favorite', models.BooleanField(default='', verbose_name='favorite')),
                ('cart', models.BooleanField(default='', verbose_name='cart')),
                ('wished_qty', models.PositiveIntegerField(default=0, verbose_name='wished qty')),
                ('buied_qty', models.PositiveIntegerField(default=0, verbose_name='buied qty')),
                ('comic', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='e_commerce.comic', verbose_name='Comic')),
            ],
            options={
                'db_table': 'e_commerce_wish_list',
            },
        ),
    ]
