# Generated by Django 3.2.2 on 2021-06-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiTabla',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Columna_x', models.CharField(default='algo', max_length=120, verbose_name='Columna de ejemplo')),
            ],
            options={
                'db_table': 'mi_tabla',
            },
        ),
        migrations.RemoveField(
            model_name='wish_list',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wish_list',
            name='name',
        ),
    ]
