# Generated by Django 3.2.2 on 2022-08-30 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_commerce', '0002_wish_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish_list',
            name='user_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user_iD'),
        ),
        migrations.AlterField(
            model_name='wish_list',
            name='comic',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='e_commerce.comic', verbose_name='comic_id'),
        ),
    ]
