# Generated by Django 3.2.2 on 2021-06-19 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_auto_20210618_0447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiTabla',
        ),
    ]
